version: '3.4'

services:

  rds.nginx:
    image: rds-nginx:1
    container_name: rds-nginx
    restart: always
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "8000:80"


     
        

 

  

